# AI Box - Локальное развертывание
# Использует образы из папки services

services:
  # AI Box Gateway - единая точка входа
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: aibox-gateway
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aibox
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - API_TOKEN=your-api-token-here
      - SECRET_KEY=your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - aibox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG Service - документооборот и поиск
  rag:
    build:
      context: ./services/rag
      dockerfile: Dockerfile
    container_name: aibox-rag
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aibox
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aibox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_API_BASE=http://ollama:11434
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - aibox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Agents Service - интеллектуальные агенты
  agents:
    build:
      context: ./services/agents
      dockerfile: Dockerfile
    container_name: aibox-agents
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aibox
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aibox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - OLLAMA_API_BASE=http://ollama:11434
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - aibox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama - локальные языковые модели
  ollama:
    build:
      context: ./services/ollama
      dockerfile: Dockerfile
    container_name: aibox-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    networks:
      - aibox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

  # PostgreSQL - основная база данных
  postgres:
    image: postgres:15
    container_name: aibox-postgres
    environment:
      POSTGRES_DB: aibox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aibox-network
    restart: unless-stopped

  # Qdrant - векторная база данных
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aibox-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__ENABLE_CORS: true
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aibox-network
    restart: unless-stopped

  # Prometheus - сбор метрик
  prometheus:
    build:
      context: ./services/monitoring
      dockerfile: Dockerfile
    container_name: aibox-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - aibox-network
    restart: unless-stopped
    depends_on:
      - gateway
      - rag
      - agents

  # Grafana - дашборды мониторинга
  grafana:
    image: grafana/grafana:latest
    container_name: aibox-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - aibox-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  postgres-data:
    driver: local
  qdrant-data:
    driver: local
  ollama-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  aibox-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
