apiVersion: v2
name: ai-box
description: Enterprise AI Box - Containerized AI Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - llm
  - rag
  - agents
  - ollama
home: https://github.com/company/ai-box
sources:
  - https://github.com/company/ai-box
maintainers:
  - name: AI Box Team
    email: team@company.com
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: qdrant
    version: 0.7.0
    repository: https://qdrant.github.io/qdrant-helm
    condition: qdrant.enabled
