{{- if .Values.ollama.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aibox.fullname" . }}-ollama
  labels:
    {{- include "aibox.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  serviceName: {{ include "aibox.fullname" . }}-ollama
  replicas: {{ .Values.ollama.replicas }}
  selector:
    matchLabels:
      {{- include "aibox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        {{- include "aibox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ollama
    spec:
      containers:
      - name: ollama
        image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          {{- toYaml .Values.ollama.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: ollama-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.ollama.persistence.size }}
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aibox.fullname" . }}-postgresql
  labels:
    {{- include "aibox.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "aibox.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "aibox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "aibox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "aibox.fullname" . }}-secrets
              key: postgres-password
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
---
{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aibox.fullname" . }}-qdrant
  labels:
    {{- include "aibox.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  serviceName: {{ include "aibox.fullname" . }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      {{- include "aibox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: qdrant
  template:
    metadata:
      labels:
        {{- include "aibox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
    spec:
      containers:
      - name: qdrant
        image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 6333
          protocol: TCP
        - name: grpc
          containerPort: 6334
          protocol: TCP
        volumeMounts:
        - name: qdrant-data
          mountPath: /qdrant/storage
        resources:
          {{- toYaml .Values.qdrant.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: qdrant-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.qdrant.persistence.size }}
{{- end }}