# AI Box - Основные переменные для развертывания

# Версии сервисов
aibox_version: "1.0.0"
docker_version: "20.10"
docker_compose_version: "2.20.0"

# Настройки приложения
aibox_user: "{{ ansible_user }}"
aibox_home: "/opt/aibox"
aibox_data_dir: "{{ aibox_home }}/data"
aibox_logs_dir: "{{ aibox_home }}/logs"
aibox_backup_dir: "{{ aibox_home }}/backups"

# Порты сервисов
gateway_port: 5000
postgres_port: 5432
qdrant_port: 6333
ollama_port: 11434
prometheus_port: 9090
grafana_port: 3000

# База данных
postgres_db: "aibox"
postgres_user: "postgres"
postgres_password: "{{ vault_postgres_password | default('secure_aibox_password_2024') }}"

# Настройки безопасности
firewall_enabled: true
allowed_ports:
  - 22    # SSH
  - 80    # HTTP
  - 443   # HTTPS
  - "{{ gateway_port }}"
  - "{{ grafana_port }}"
  - "{{ prometheus_port }}"

# Модели Ollama для загрузки
ollama_models:
  - "llama3.2:3b"
  - "codellama:7b"
  - "mistral:7b"

# Настройки мониторинга
grafana_admin_password: "{{ vault_grafana_password | default('admin') }}"
prometheus_retention: "30d"

# Docker настройки
docker_users:
  - "{{ ansible_user }}"

# Systemd настройки
aibox_service_enabled: true
aibox_service_state: started

# Backup настройки
backup_schedule: "0 2 * * *"  # каждый день в 2:00
backup_retention_days: 30