apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: ai-box
  labels:
    app: ollama
    component: llm
spec:
  serviceName: ollama
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
      - name: model-downloader
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          mkdir -p /models
          # Download models if not present
          if [ ! -f /models/llama3.2-3b.gguf ]; then
            echo "Downloading models..."
            # Models will be pulled by Ollama service
          fi
        volumeMounts:
        - name: ollama-models
          mountPath: /models
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_MODELS
          value: "/root/.ollama/models"
        - name: OLLAMA_KEEP_ALIVE
          value: "24h"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: ollama-models
          mountPath: /root/.ollama/models
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: ollama-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: ollama-models
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ai-box
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: ai-box
data:
  models.txt: |
    llama3.2:3b
    llama3.2:1b
    codellama:7b
  pull-models.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for Ollama service to be ready..."
    while ! curl -f http://localhost:11434/api/tags >/dev/null 2>&1; do
      sleep 5
    done
    
    echo "Ollama service is ready. Pulling models..."
    while IFS= read -r model; do
      if [ -n "$model" ] && [ "${model:0:1}" != "#" ]; then
        echo "Pulling model: $model"
        ollama pull "$model"
      fi
    done < /config/models.txt
    
    echo "All models pulled successfully."
