apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: ai-box
  labels:
    app: qdrant
    component: vector-db
spec:
  serviceName: qdrant
  replicas: 3
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        - name: QDRANT__CLUSTER__ENABLED
          value: "true"
        - name: QDRANT__CLUSTER__P2P__PORT
          value: "6335"
        - name: QDRANT__STORAGE__STORAGE_PATH
          value: "/qdrant/storage"
        - name: QDRANT__STORAGE__SNAPSHOTS_PATH
          value: "/qdrant/snapshots"
        - name: QDRANT__LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
        - name: qdrant-snapshots
          mountPath: /qdrant/snapshots
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: qdrant-snapshots
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: ai-box
  labels:
    app: qdrant
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: http
  - name: grpc
    port: 6334
    targetPort: grpc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: ai-box
  labels:
    app: qdrant
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: http
  - name: grpc
    port: 6334
    targetPort: grpc
  - name: p2p
    port: 6335
    targetPort: 6335
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: ai-box
data:
  production.yaml: |
    debug: false
    log_level: INFO
    
    service:
      host: 0.0.0.0
      http_port: 6333
      grpc_port: 6334
      enable_cors: true
      max_request_size_mb: 32
      max_workers: 0
    
    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 100
    
    storage:
      # Write-ahead-log related configuration
      wal:
        wal_capacity_mb: 32
        wal_segments_ahead: 0
      
      # Normal segment related configuration  
      performance:
        max_search_threads: 0
        max_optimization_threads: 0
      
      # Optimizer configuration
      optimizers:
        deleted_threshold: 0.2
        vacuum_min_vector_number: 1000
        default_segment_number: 0
        max_segment_size_kb: 200000
        memmap_threshold_kb: 200000
        indexing_threshold_kb: 20000
        payload_indexing_threshold_kb: 10000
        flush_interval_sec: 5
        max_optimization_threads: 1
    
    # TLS configuration (disabled for internal cluster communication)
    tls:
      cert: null
      key: null
