apiVersion: v2
name: postgresql
description: PostgreSQL Database for AI Box
type: application
version: 12.1.9
appVersion: "15.4.0"
keywords:
  - postgresql
  - database
  - sql
home: https://www.postgresql.org/
sources:
  - https://github.com/postgres/postgres
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
