---
# AI Box - Развертывание на удаленном сервере
# Полная автоматизация установки на single server

- name: "AI Box - Серверное развертывание"
  hosts: aibox_servers
  become: yes
  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - name: "🔍 Проверка системных требований"
      assert:
        that:
          - ansible_facts['memtotal_mb'] >= 2048
          - ansible_facts['processor_vcpus'] >= 2
        fail_msg: "Недостаточно ресурсов для AI Box (нужно минимум 2GB RAM, 2 CPU)"

    - name: "📊 Вывод информации о системе"
      debug:
        msg: 
          - "Сервер: {{ inventory_hostname }}"
          - "ОС: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
          - "RAM: {{ (ansible_facts['memtotal_mb'] / 1024) | round(1) }}GB"
          - "CPU: {{ ansible_facts['processor_vcpus'] }} cores"

  tasks:
    - name: "🔄 Обновление системы"
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: "📦 Установка базовых пакетов"
      package:
        name:
          - curl
          - wget
          - git
          - unzip
          - htop
          - net-tools
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    - name: "🐳 Установка Docker"
      include_tasks: tasks/install-docker.yml

    - name: "📂 Создание директорий AI Box"
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - /opt/aibox
        - /opt/aibox/config
        - /opt/aibox/data
        - /opt/aibox/logs
        - /opt/aibox/backups

    - name: "📥 Копирование файлов проекта"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0644') }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - { src: ../docker-compose.yml, dest: /opt/aibox/docker-compose.yml }
        - { src: ../docker-compose.prod.yml, dest: /opt/aibox/docker-compose.prod.yml }
        - { src: ../config/, dest: /opt/aibox/config/ }
        - { src: ../scripts/, dest: /opt/aibox/scripts/, mode: '0755' }
        - { src: ../demo_gateway.py, dest: /opt/aibox/demo_gateway.py }

    - name: "⚙️ Создание .env файла"
      template:
        src: templates/env.j2
        dest: /opt/aibox/.env
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "🚀 Запуск AI Box сервисов"
      shell: |
        cd /opt/aibox
        docker-compose -f docker-compose.prod.yml down || true
        docker-compose -f docker-compose.prod.yml up -d
      become_user: "{{ ansible_user }}"

    - name: "⏳ Ожидание готовности сервисов"
      wait_for:
        port: "{{ item }}"
        host: "localhost"
        delay: 10
        timeout: 120
      loop:
        - 5000  # Gateway
        - 5432  # PostgreSQL
        - 6333  # Qdrant
        - 11434 # Ollama

    - name: "🤖 Инициализация Ollama моделей"
      shell: |
        docker exec aibox-ollama ollama pull llama3.2:3b
        docker exec aibox-ollama ollama pull codellama:7b
      become_user: "{{ ansible_user }}"
      ignore_errors: yes

    - name: "🔒 Настройка firewall"
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22    # SSH
        - 80    # HTTP
        - 443   # HTTPS
        - 5000  # AI Box Gateway
        - 3000  # Grafana
        - 9090  # Prometheus
      when: ansible_facts['os_family'] == "Debian"

    - name: "🔥 Включение firewall"
      ufw:
        state: enabled
        policy: deny
        direction: incoming
      when: ansible_facts['os_family'] == "Debian"

    - name: "⚙️ Создание systemd сервиса"
      template:
        src: templates/aibox.service.j2
        dest: /etc/systemd/system/aibox.service
        mode: '0644'
      notify: reload systemd

    - name: "🚀 Включение автозапуска AI Box"
      systemd:
        name: aibox
        enabled: yes
        state: started
        daemon_reload: yes

    - name: "✅ Проверка состояния сервисов"
      shell: |
        cd /opt/aibox
        docker-compose -f docker-compose.prod.yml ps
      become_user: "{{ ansible_user }}"
      register: services_status

    - name: "📊 Вывод состояния сервисов"
      debug:
        msg: "{{ services_status.stdout_lines }}"

    - name: "🌐 Проверка доступности API"
      uri:
        url: "http://localhost:5000/health"
        method: GET
        timeout: 10
      register: health_check
      retries: 3
      delay: 5

    - name: "📋 Информация о развертывании"
      debug:
        msg:
          - "✅ AI Box успешно развернут на сервере!"
          - "🌐 Доступ: http://{{ inventory_hostname }}:5000"
          - "📖 API документация: http://{{ inventory_hostname }}:5000/docs" 
          - "📊 Мониторинг: http://{{ inventory_hostname }}:3000"
          - "🔍 Логи: docker-compose -f /opt/aibox/docker-compose.prod.yml logs -f"
          - "💾 Бэкап: /opt/aibox/scripts/backup.sh"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes