global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-box-gateway'
    static_configs:
      - targets: ['gateway:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ai-box-rag'
    static_configs:
      - targets: ['rag:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'ai-box-agents'
    static_configs:
      - targets: ['agents:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    scrape_interval: 30s

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s